### ISSUE TITLE
about Microbit V2

### ISSUE THREAD

**Issue by YzmsLinq** [rhubarbdog/microbit-dht11#1]
It doesn't work normally in microbit V2, and it can't read data all the time

**Comment by rhubarbdog** [comment]
Yes the problem is the cpu on the v2 is 64mhz where as on v1 it only 16mhz. I don't have much tech at the moment so won't be fixing this for a while

**Comment by YzmsLinq** [comment]
Thank you for your reply, and hope to resolve this issue as soon as possible.

**Comment by MeqdadDev** [comment]
Hello guys,
Any updates about working with micro:bit v2 with DHT11?

Thanks for your efforts.

**Comment by MeqdadDev** [comment]
Hi dears,

For those who are working with some hardware sensors and modules with micro:bit v2, I would like to recommend this repo for you: [BBC micro:bit with MicroPython](https://github.com/MeqdadDev/microbit-micropython-samples)
Where I modularized and prepared some micro:bit projects using MicroPython.

**Comment by rhubarbdog** [comment]
hi the new code is done tested and available to clone and use. use the correct code for the microbit you have
